#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill /home/lain/Pictures/random/paper2.jpg &
xrandr --output HDMI1 --mode 1366x768 &
~/polybar-collection/launch.sh &
xrdb -load ~/.config/.Xresources &

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7

# Other stuff
bspc rule -a firefox border_width 0
bspc config border_width         3
bspc config window_gap           3
bspc config split_ratio          0.618
bspc config top_padding          0
bspc config bottom_padding       18
bspc config left_padding         3
bspc config right_padding        3
bspc config normal_border_color "#1e1e1e"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#685e57"
bspc config presel_feedback_color "#1e1e1e"
bspc config focus_follows_pointer true

